### ISSUE TITLE
Cloc Diff With File Pairs.

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#464] opened 2020-01-31 11:15 UTC
We have been testing Cloc to detect diff between our product versions.
It works great, kudos to you and the contributors.

In some of our versions, the files are renamed / moved around for `refactoring` purposes which skews the difference analysis. We have implemented a `Rename / Move Tracking` algorithm to track file between renames and moves.

Right now we need to run cloc on whole repositories, Repo A and Repo B. Since cloc cannot identify the renames / moves so we need to run CLOC again on individual files which we tracked as renames. 

Would it be possible if cloc can accept input in pairs having exact path of file A and file B.
eg,
```
cloc --diff --diff-input=input.txt
```

input.txt would be like

```
'c:\\fileA.txt,c:\\folder\\fileB.txt'
'c:\\fileM.txt,c:\\folder\\fileN.txt'
```

That way we can run CLOC once per repo and improve performance.

**Comment by AlDanial** [comment] 2020-02-01 04:12
Duplicate of #455

**Closed by AlDanial** 2020-02-01 04:12 UTC
