### ISSUE TITLE
--diff does not support tags?

### ISSUE THREAD

**Issue by PMExtra** [AlDanial/cloc#796] opened 2023-11-23 10:07 UTC
**Describe the bug**

When I executed `cloc --diff 1.0.0 HEAD`, I got the error:

```
Error: incorrect length fh array when preparing diff at step 6.
```

But `cloc --diff $(git rev-list -n 1 1.0.0) HEAD` can work as expected. (sha of the tag)

**Comment by AlDanial** [comment] 2023-11-23 17:10
cloc supports git tags -- but you need to tell cloc to be in git mode.  Try
<pre>
cloc --git --diff 1.0.0 HEAD
</pre>

**Comment by PMExtra** [comment] 2023-11-24 01:29
It works with `--git` option, but there are some confusing error messages that outputs from `cloc`:

```
fatal: ref HEAD is not a symbolic ref
```

The full outputs:
```
> /usr/src/cloc --git --diff 2.0.0-beta.1 HEAD
fatal: ref HEAD is not a symbolic ref
fatal: ref HEAD is not a symbolic ref
     132 text files.
     143 text files.
     146 files ignored.                             

github.com/AlDanial/cloc v 1.98  T=0.20 s (372.3 files/s, 20876.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#
 same                            0              0             31           2188
 modified                       48              0              0            175
 added                          15            168             11           1057
 removed                         4             46              1            312
JSON
 same                            0              0              0            186
 modified                        6              0              0              0
 added                           0              0              0             12
 removed                         0              0              0              0
MSBuild script
 same                            0              0              0             14
 modified                        1              0              0              0
 added                           0              0              0              1
 removed                         0              0              0              0
XML
 same                            0              0              0              2
 modified                        1              0              0              1
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0             31           2390
 modified                       56              0              0            176
 added                          15            168             11           1070
 removed                         4             46              1            312
-------------------------------------------------------------------------------
> 
```

**Comment by AlDanial** [comment] 2023-11-24 18:08
I'm unable to reproduce that.  Running `cloc --git --diff v1.96 HEAD` on the cloc git repo shows clean output.

**Comment by AlDanial** [comment] 2023-11-25 01:27
Bottom line is cloc supports git tags so closing this.

**Closed by AlDanial** 2023-11-25 01:27 UTC
