### ISSUE TITLE
Complex regular subexpression recursion limit (32766) exceeded at /tmp/cloc line 4946.

### ISSUE THREAD

**Issue by c02y** [AlDanial/cloc#245] opened 2017-11-23 01:56 UTC
When I use the bf30f55 version  (v1.75) of cloc in ffmpeg tar source directory, multiple lines of the same message were printed in the result of cloc.

When I use the 1.74 version of cloc in the same directory, the similar multiple lines of message were printed in the result:

    Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 4871.

**Comment by AlDanial** [comment] 2017-11-26 21:29
I'm unable to duplicate the problem with ``ffmpeg-3.4.tar.bz2`` (from http://ffmpeg.org/releases/ffmpeg-3.4.tar.bz2) and the cloc development version.  Here's the output I see:
<pre>
    6563 text files.  
    6424 unique files.                                                                     
    2888 files ignored.                      

github.com/AlDanial/cloc v 1.75  T=35.04 s (104.9 files/s, 40076.5 lines/s)                
-----------------------------------------------------------------------------------        
Language                         files          blank        comment           code        
-----------------------------------------------------------------------------------        
C                                 2415         127265         107242         851191        
C/C++ Header                       896          16261          51952         116855        
Assembly                           254           9516          11058          92502        
Bourne Shell                        24            939            417           7706        
make                                40            299             72           3699        
C++                                  3            264            116           1623        
Objective C                          2            302            117           1318        
Perl                                 7            254            346            992        
XSD                                  1             42              4            333        
Windows Resource File                9             27            198            270        
CUDA                                 2             25             54            212        
Markdown                             4             39              0            150        
CSS                                  3             31             22            140        
Verilog-SystemVerilog                9              0              0             75        
awk                                  1              6              5             53        
Ruby                                 1              9              0             52        
Python                               2              8              0             51        
HTML                                 1              5              4             44        
YAML                                 1              0              0             26        
-----------------------------------------------------------------------------------        
SUM:                              3675         155292         171607        1077292        
-----------------------------------------------------------------------------------        
</pre>

**Comment by c02y** [comment] 2017-11-27 03:29
https://ffmpeg.org/releases/ffmpeg-3.2.7.tar.xz

    >> cd ffmpeg-3.2.7/
    >> cloc .
        6169 text files.
        6039 unique files.
    Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 4871.
    Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 4871.
    .... more than 200 lines of the same centences 
    Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 4871.
    Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 4871.
        2725 files ignored.
    
    github.com/AlDanial/cloc v 1.74  T=31.66 s (108.8 files/s, 41439.9 lines/s)
    -----------------------------------------------------------------------------------
    Language                         files          blank        comment           code
    -----------------------------------------------------------------------------------
    C                                 2265         118495         102609         799074
    C/C++ Header                       845          15362          49171         114475
    Assembly                           227           7521           9189          76917
    Bourne Shell                        23            895            368           7369
    make                                41            297             73           3500
    Objective C                          3            385            152           1562
    C++                                  3            199             89           1123
    Perl                                 7            254            346            992
    XSD                                  1             41              4            314
    Windows Resource File                9             27            198            270
    Markdown                             4             39              0            152
    CSS                                  3             31             22            140
    Verilog-SystemVerilog                9              0              0             75
    Python                               2              8              0             51
    HTML                                 1              5              4             44
    YAML                                 1              0              0             26
    -----------------------------------------------------------------------------------
    SUM:                              3444         143559         162225        1006084
    -----------------------------------------------------------------------------------

Using the latest version of cloc (v1.75), the only different lines are:

    Complex regular subexpression recursion limit (32766) exceeded at /tmp/cloc line 4946.
    ...
    github.com/AlDanial/cloc v 1.75  T=31.19 s (110.4 files/s, 42060.7 lines/s)

**Comment by AlDanial** [comment] 2017-12-01 19:00
I grabbed the 3.2.7 release and tried again, still worked fine:
<pre>
> cloc ffmpeg-3.2.7.tar.gz 
    6186 text files.
    6057 unique files.                                          
    2742 files ignored.

github.com/AlDanial/cloc v 1.75  T=18.44 s (186.8 files/s, 71141.5 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C                                 2265         118495         102609         799074
C/C++ Header                       845          15362          49171         114475
Assembly                           227           7521           9189          76917
Bourne Shell                        23            895            368           7369
make                                41            297             73           3500
Objective C                          3            385            152           1562
C++                                  3            199             89           1123
Perl                                 7            254            346            992
XSD                                  1             41              4            314
Windows Resource File                9             27            198            270
Markdown                             4             39              0            152
CSS                                  3             31             22            140
Verilog-SystemVerilog                9              0              0             75
Python                               2              8              0             51
HTML                                 1              5              4             44
YAML                                 1              0              0             26
-----------------------------------------------------------------------------------
SUM:                              3444         143559         162225        1006084
-----------------------------------------------------------------------------------
</pre>

What do you get for ``perl --version`` ?  I used v5.22.1 and v5.26.0 with the same results.

**Comment by c02y** [comment] 2017-12-04 01:04
> What do you get for perl --version ? I used v5.22.1 and v5.26.0 with the same results.

     $ perl --version
     This is perl, v5.10.1 (*) built for i386-linux-thread-multi

**Comment by liviuchircu** [comment] 2017-12-06 14:18
Getting a similar issue with `master`, bea2eded8c0:

```
$ cloc .
    9142 text files.
    8482 unique files.                                          
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 5253.
    2348 files ignored.

github.com/AlDanial/cloc v 1.75  T=30.66 s (224.5 files/s, 90157.4 lines/s)
```

Cloned project is `https://freeswitch.org/stash/scm/fs/freeswitch.git`, `master - 14803625195`.

**Comment by stsnel** [comment] 2017-12-08 10:09
I can reproduce the issue with the ffmpeg tarball on the CentOS 6.0 LiveDVD (which has perl 5.10.1). I'm also able to reproduce the error messages when running cloc on the freeswitch repository.

The root cause seems to be a line that matches regular expression '([0-9]+.*)+\s+/' on C source code. This causes problems on some source code lines which contain large numbers. It also seems to inflate the comment line count.The line which contains this regexp was added in commit https://github.com/AlDanial/cloc/commit/295b64391e09571c1b25e01bd2ce59c3feb5d889

It seems that this line is no longer needed, as far as I can tell. I have pushed a tentative fix for this issue to https://github.com/stsnel/cloc/tree/remove-regexp-c  (which just removes the line). 

Note: the "Complex regular subexpression recursion limit"  error can still occur in some other situations. This only fixes the cause of the error message for these two repositories. 

@AlDanial: If you'd like to receive a pull request for this change, please let me know.

**Comment by AlDanial** [comment] 2017-12-09 17:57
@stsnel -- great detective work.  That regex should have never have been committed!

Regarding "Complex regular subexpression recursion limit", the problem is nearly always triggered when there are comment markers within text strings, which leads to unbalanced regex's. I have a general fix in mind but it isn't ready yet.

**Comment by hatzopoulos** [comment] 2018-06-26 22:07
I got a similar error trying this software out for the first time on our closed source software.

```
    4588 text files.
    3426 unique files.
Complex regular subexpression recursion limit (32766) exceeded at /bin/cloc line 9998.
    1389 files ignored.

github.com/AlDanial/cloc v 1.76  T=281.03 s (11.4 files/s, 49754.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
LESS                           391        1518786         225172        7157142
CSS                            412          13068          10652        4207413
JavaScript                     549         100942         112747         350940
PHP                           1130          33373          50681         111868
Smarty                         348          10012            720          46757
HTML                           143           2336             55          14884
SQL                            108            562            924          10914
JSON                           122              1              0           1316
C                                1             78             12            389
ASP                              2             37             18            193
Markdown                         3             26              0             66
ColdFusion                       1             19              0             56
Bourne Shell                     1              1              0             22
XML                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                          3212        1679241         400981       11901964
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment] 2018-06-29 15:39
@hatzopoulos : I won't be able to help without access to the code which causes the warning.  If you wish to pursue this further, first isolate the problem file.  One way is to run cloc with ``-v 3 --by-file`` then watch for the file name when the warning appears.  
If possible, obfuscate the code in a way that still shows the error, then send it to me.  If not possible, try to isolate the problematic line of code by stripping out pieces at a time.

**Comment by AlDanial** [comment] 2018-06-29 23:20
Commit 01ace37 adds a new switch, ``--strip-str-comments``, that tries to mask comment markers embedded in strings.  This should fix most instances of _Complex regular subexpression recursion limit_, at the cost of slower performance by cloc.
Please report any failures using this switch and I'll investigate further.

**Closed** 2018-07-16 04:08 UTC

**Comment by hatzopoulos** [comment] 2018-07-17 15:37
@AlDanial,

Success. I tried today's version again with `cloc --strip-str-comments` and it completed without errors. It also went way faster than my previous attempts. `60` versus `281` seconds.

```
   10892 text files.
   10479 unique files.
    1514 files ignored.

github.com/AlDanial/cloc v 1.77  T=60.19 s (156.9 files/s, 25376.7 lines/s)
```

**Comment by AlDanial** [comment] 2018-07-18 02:31
@hatzopoulos: thanks for the feedback!

As you probably know, the first run was slower because it spent most of its time in a regex recursion loop.  The new switch alters the input to (try to) remove character patterns which trigger the recursion.  I am surprised by the 4.5 x speed difference though, didn't think it would be so large.

**Comment by tkstorm** [comment] 2019-06-11 09:25
```
$ cloc .
   12430 text files.
   12158 unique files.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.82/libexec/bin/cloc line 9334.
    1469 files ignored.

github.com/AlDanial/cloc v 1.82  T=38.99 s (283.7 files/s, 53292.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
PHP                            7025         149600         262147         633578
C++                             274          24258          25213         160271
SVG                             296            714             27          86038
Java                            204          11325          21744          69243
C/C++ Header                    309          15128          38231          60391
...
```

I have got the same problem when count a large files project.

**Comment by AlDanial** [comment] 2019-06-14 03:08
Try ``cloc --strip-str-comments .``

**Comment by oviliz** [comment] 2020-11-20 14:09
@AlDanial, I'm getting the same on some repositories after installing 1.88 via NPM
`Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 12076.`

Not getting this when using the 1.60 version included in Ubuntu 16.04 but in that case, the results are different too.
