### ISSUE TITLE
Ignores exclude-dir option when using * for file match

### ISSUE THREAD

**Issue by jdforsythe** [AlDanial/cloc#82] opened 2016-04-06 14:13 UTC
I installed cloc with:

```
npm install -g cloc
```

Given a folder structure:

```
./test.js
./lib/lib.js
```

When I execute:

```
$ cloc --skip-uniqueness --by-file --exclude-dir=lib *
       2 text files.
       2 unique files.
       1 file ignored.

https://github.com/AlDanial/cloc v 1.66  T=0.02 s (103.0 files/s, 103.0 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
test.js                              0              0              1
lib/lib.js                           0              0              1
-------------------------------------------------------------------------------
SUM:                                 0              0              2
-------------------------------------------------------------------------------
```

The program ignores the exclude-dir option. If I substitute `*` for `.`:

```
$ cloc --skip-uniqueness --by-file --exclude-dir=lib .
       1 text file.
       1 unique file.
       1 file ignored.

https://github.com/AlDanial/cloc v 1.66  T=0.02 s (53.8 files/s, 53.8 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
./test.js                            0              0              1
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment] 2016-04-11 01:13
git commit 01784ca has a fix for this specific problem but I'm leaving this issue open since a similar issue will happen with --not-match-d, need to add that fix too.

**Comment by milasudril** [comment] 2016-05-13 08:43
I hope this bug gets fixed. In the meantime

    cloc !(excluded-dir)

works in bash

**Comment by AlDanial** [comment] 2016-05-14 18:49
The `--exclude-dir` bug was fixed two weeks ago (https://github.com/AlDanial/cloc/commit/01784caf236cfa7ea038d5d1b8c5ee2c76c9e0c4); I'd be grateful if one of you confirmed that.  The related `--not-match-d` will get the same treatment once.

**Comment by AlDanial** [comment] 2016-05-20 23:13
Added tests to Unix/t/01_opts.t to verify both ``--not-match-d`` and ``--exclude-dir`` work when ``*`` is passed as an input argument.

**Closed by AlDanial** 2016-05-20 23:13 UTC
Labels: bug
