### ISSUE TITLE
Add support for Gleam source code.

### ISSUE THREAD

**Issue by pd-andy** [AlDanial/cloc#586] opened 2021-04-07 14:54 UTC
**If you want an unsupported language added, provide:**
 - language name: Gleam
 - file extension(s): `.gleam`
 - method(s) of commenting text: Gleam only uses `//` for single line comments, there's no multi-line comment syntax. Additional forward slashes (eg `///` and `////`) are used for generating documentation from comments, but I don't think that's relevant here.
 - location of sample code:
    - https://github.com/gleam-lang/stdlib/blob/main/src/gleam/list.gleam

Gleam projects also typically have an Erlang [application resource file](https://erlang.org/doc/man/app.html) with the extension `.app.src` and a `rebar.config` file, but it looks like those are already supported thanks to Erlang support.

**Comment by AlDanial** [comment] 2021-04-10 19:26
Duplicate of https://github.com/AlDanial/cloc/issues/550; support exists in the current development version.

**Closed by AlDanial** 2021-04-10 19:26 UTC
