### ISSUE TITLE
cloc.1 man page fails to build on non-linux UNIXes

### ISSUE THREAD

**Issue by mitchblank** [AlDanial/cloc#571] opened 2021-03-03 01:55 UTC
See https://github.com/Homebrew/homebrew-core/issues/72328

The 025a17d6aa57de5ec53729bbcd1f455c7e9d9793 change by @jelly to enable reproducible builds added a requirement that `/bin/date` accept GNU-style long options.  This means on OS/X (and probably most other non-linux UNIXes) the pod2man will fail and leave behind an empty `cloc.1` file:
```
LC_ALL= LANG=C pod2man --utf8 \
		--center="User Commands" \
		--date="$(date --utc --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" "+%Y-%m-%d")" \
		--name="cloc" \
		--section="1" \
		cloc.1.pod \
	| sed 's,[Pp]erl v[0-9.]\+,cloc,' \
	  > cloc.1 && \
	rm -f pod*.tmp
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Option date requires an argument
```

FWIW, on OS/X specifically the `--utc --date=XXX` can be replaced with `-r XXX` but that's not fully portable either.

**Comment by AlDanial** [comment] 2021-03-10 04:17
https://github.com/Homebrew/homebrew-core/pull/72358 suggests a work-around to this problem was implemented on the Homebrew side.  Is that sufficient for me to close this?

**Comment by mitchblank** [comment] 2021-03-10 04:23
Well you are the package maintainer, so it's up to you.

The package definitely does not work out-of-the box on non-linux operating systems.  OS/X is just one, you'd probably have had the same issue on FreeBSD, Solaris, etc.

And, of course, it won't work if you just install on OS/X from source rather than via homebrew.

The patch I made to homebrew fixed the user-reported problem there, but I'd be happy to remove it when-and-if the underlying bug in cloc is fixed.

**Comment by AlDanial** [comment] 2021-03-10 05:56
I'll update ``pod2man.mk`` to make it more portable.  May be a while since I don't have ready access to non-Linux Unix boxes.

**Comment by jelly** [comment] 2021-03-10 16:13
The issue is I guess due to the usage of BSD date, the [reproducible builds documentation](https://reproducible-builds.org/docs/source-date-epoch/) has some information about it:

```For GNU systems:

BUILD_DATE="$(date --utc --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y-%m-%d)"
If you need to support BSD date as well you should fallback to trying ther -r seconds timestamp variant:

DATE_FMT="+%Y-%m-%d"
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(date +%s)}"
BUILD_DATE=$(date -u -d "@$SOURCE_DATE_EPOCH" "$DATE_FMT" 2>/dev/null || date -u -r "$SOURCE_DATE_EPOCH" "$DATE_FMT" 2>/dev/null || date -u "$DATE_FMT")
```

**Comment by AlDanial** [comment] 2021-03-11 03:36
@MichaelDimmitt : does @jelly 's solution work for you?

**Closed** 2021-03-14 18:04 UTC

**Comment by MichaelDimmitt** [comment] 2021-03-16 20:39
checking, if I understand correctly, 
after brew install cloc , calling the man page is failing?
