### ISSUE TITLE
alarm() with negative argument at ./cloc line 5867.

### ISSUE THREAD

**Issue by ShnurD6** [AlDanial/cloc#446] opened 2019-12-30 17:01 UTC
In last release (51847c3, 1.84) branch, execute command 
`./cloc ~/Work/my/my_project --diff-timeout 0 --timeout 0`
causes the program to throw an error 
`alarm() with negative argument at ./cloc line 5867.`

It produces approximately 650,000 such errors, and then ends

If I switch branch to master, the error is similar:
`alarm() with negative argument at ./cloc line 5908.`

plz help)

**Comment by AlDanial** [comment] 2020-01-10 16:07
This is puzzling.  I'm unable to duplicate the problem but I think it has to do with the contents of one (or more) of your files.  If you do a git pull to grab the latest master (I'm at 5d128014b but will probably be making commits later today), you'll find the offending code in this block:

<pre>
 5914         my $max_duration_sec = scalar(@lines)/1000.0; # est lines per second
 5915            $max_duration_sec = 1.0 if $max_duration_sec < 1;
 5916         if (defined $opt_timeout) {
 5917             $max_duration_sec = $opt_timeout if $opt_timeout > 0;
 5918         }
 5919 #my $T_start = Time::HiRes::time();
 5920         eval {
 5921             local $SIG{ALRM} = sub { die "alarm\n" };
 5922             alarm $max_duration_sec;
 5923             no strict 'refs';
 5924             @lines = &{$subroutine}(\@lines, @args);   # apply filter...
 5925             alarm 0;
 5926         };
</pre>

If you rerun with this version of the code the error should appear at 5922.  The question is how can ``$max_duration_sec`` be negative?

Please edit your version of the code to include the extra lines shown here:

<pre>
 5914         my $max_duration_sec = scalar(@lines)/1000.0; # est lines per second
 5915            $max_duration_sec = 1.0 if $max_duration_sec < 1;
 5916         if (defined $opt_timeout) {
 5917             $max_duration_sec = $opt_timeout if $opt_timeout > 0;
 5918         }
 5919 #my $T_start = Time::HiRes::time();

      if ($max_duration_sec < 0) {
          print "MDS=$max_duration_sec      file=$file    opt_timeout=$opt_timeout\n";
          die;
      }

 5920         eval {
 5921             local $SIG{ALRM} = sub { die "alarm\n" };
 5922             alarm $max_duration_sec;
 5923             no strict 'refs';
 5924             @lines = &{$subroutine}(\@lines, @args);   # apply filter...
 5925             alarm 0;
 5926         };
</pre>

then run and see what the output is.  If possible, I'd like to get the file that triggers this.

**Comment by AlDanial** [comment] 2020-02-18 03:30
Closing--inability to replicate.

**Comment by tefger** [comment] 2020-09-15 08:51
Same problem for me with v1.88:
alarm() with negative argument at ./cloc line 6211.

It disappears for me when setting --timeout > 0, e.g. --timeout 99999

**Comment by AlDanial** [comment] 2020-09-16 04:33
I'm keen to fix this once and for all but I won't be able to unless I can replicate it.  Is the code you're counting publicly available?

**Comment by stsnel** [comment] 2020-09-16 14:50
I am able to replicate the issue with the cloc 1.88 Windows executable on a trivial one line file:

> echo blah > hello.php
> cloc-1.88.exe --timeout 0 hello.php

I can't reproduce the issue on MacOS or Linux, so it appears to be a Windows-specific issue, rather than a file specific issue. 

The only thing I can think of is that the rather high default timeout value at https://github.com/AlDanial/cloc/blob/a4f9037d2a7f69406a8eabdc0e3553f093b254e9/cloc#L968 results in an overflow of the alarm value. If you like, I can try building a Windows executable with a lower default value, to see if that resolves the problem.

**Comment by tefger** [comment] 2020-09-16 15:43
> I'm keen to fix this once and for all but I won't be able to unless I can replicate it. Is the code you're counting publicly available?

Unfortunately not. But setting the timeout to a higher value instead of 0 is a pretty good workaround.
(I was using the Linux version under Debian)

**Comment by stsnel** [comment] 2020-09-16 17:04
> (I was using the Linux version under Debian)

That's odd ... I am also able to replicate it on Debian 10, but not on CentOS 7.

Anyway, reducing the timeout/diff-timeout value from 2ˆ31 to 2ˆ31-1 resolves the issue for me on both Debian 10 and Windows 10. I suspect the alarm parameter is stored in a signed 32 bit variable on some platforms. I've submitted a PR: https://github.com/AlDanial/cloc/pull/519

**Comment by AlDanial** [comment] 2020-09-17 03:54
@tefger can you give the development code with 2a44cc7 a try with your code base?  I've got a good feeling that @stsnel hit the nail on the head as to the cause (& fix).  Regarding Debian 10 v CentOS 7, I wonder if the former used a 32 bit Perl while the latter a 64 bit version?

**Comment by tefger** [comment] 2020-09-17 10:37
Thanks @AlDanial, this version is working properly now, tested with --timeout 0, --timeout 9999999 and without --timeout flag under Debian 10.5.0 64-bit. 👍

**Closed** 2020-09-18 01:36 UTC
