### ISSUE TITLE
Deprecated regex usage

### ISSUE THREAD

**Issue by sdicke** [AlDanial/cloc#321] opened 2018-08-15 13:56 UTC
Today I ran cloc and got the following output:

Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/({ <-- HERE |})/ at /usr/bin/cloc line 8555.

**Comment by AlDanial** [comment] 2018-08-16 03:44
Duplicate of #307 and #315; fixed in the development version.

**Closed by AlDanial** 2018-08-16 03:44 UTC
