### ISSUE TITLE
Cloc Freezes when running it on the `philburk/pforth` project

### ISSUE THREAD

**Issue by Emadpres** [AlDanial/cloc#183] opened 2017-04-07 13:32 UTC
I just cloned the [pforth project](https://github.com/philburk/pforth) and tried to run `Cloc` on it, but it keeps freezing and a `Perl` process keeps using 100% of CPU.

Since I'm using the binary version of `Cloc` I can not tell what makes it happen, but I'm reporting the bug here for the further debugging.

**Comment by AlDanial** [comment] 2017-04-08 07:31
cloc has a verbose mode that might help reveal the problem; try rerunning with <code>-v 3</code> to see where, and more importantly, on which file it hangs.

I won't be able to clone pforth to try myself for at least another week.

**Comment by Emadpres** [comment] 2017-04-08 11:50
I reran using `-v 3` option. Actually, I'm not sure about the output syntax and how I should interpret it, but here is last ~25 lines:
```
rm_comments file=./fth/coretest.fth sub=call_regexp_common
-> call_regexp_common for C++
<- call_regexp_common
-> remove_matches(pattern=^\s*$)
<- remove_matches
rm_comments file=./fth/coretest.fth sub=remove_inline
-> remove_inline(pattern=\\.*$)
-> remove_matches(pattern=^\s*$)
<- remove_matches
<- rm_comments
<- call_counter(999, 142, 38)
-> call_counter(./fth/file.fth, Forth)
-> read_file(./fth/file.fth)
<- read_file
-> rm_blanks(language=Forth)
-> remove_matches(pattern=^\s*$)
<- remove_matches
<- rm_blanks(language=Forth)
-> rm_comments(file=./fth/file.fth)
rm_comments file=./fth/file.fth sub=remove_matches
-> remove_matches(pattern=^\s*\\.*$)
<- remove_matches
-> remove_matches(pattern=^\s*$)
<- remove_matches
rm_comments file=./fth/file.fth sub=Forth_paren_to_C
-> Forth_paren_to_C()
```
It hangs on the last line and the `perl5.24` process use 100% of one of my cpu core forver. This the list of open files for this process:
```
cwd
/Users/emadpres/testGit/pforth
txt
/opt/local/bin/perl5.24
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/CORE/libperl.dylib
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/Fcntl/Fcntl.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/IO/IO.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/List/Util/Util.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/POSIX/POSIX.bundle
txt
/opt/local/lib/perl5/vendor_perl/5.24/darwin-thread-multi-2level/auto/Digest/MD5/MD5.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/Time/HiRes/HiRes.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/re/re.bundle
txt
/opt/local/lib/perl5/5.24/darwin-thread-multi-2level/auto/File/Glob/Glob.bundle
txt
/usr/lib/dyld
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
/dev/ttys000
1
/dev/ttys000
2
/dev/ttys000
3
/opt/local/bin/cloc
4
/private/var/folders/0s/l93tbnq9003b5yzlnyr091ph0000gn/T/QRGTUFW9l_
```

OS: MacOs 10.12.4
cloc --version: 1.72

**Comment by AlDanial** [comment] 2017-04-08 14:46
That's helpful, thanks.  What happens if you try just that last file, ie
<pre>
cloc fth/file.fth
</pre>
Does that hang?  If yes, try temporarily removing that file then run cloc on the whole repo again.

**Comment by Emadpres** [comment] 2017-04-08 15:54
Yes, It hangs on this file.

**Comment by Emadpres** [comment] 2017-04-08 17:34
Same problem in another project:
> Project: [rsennrich/Bleualign](https://github.com/rsennrich/Bleualign)
> File: `eval/eval1957.SACunidir.fr`

**Comment by AlDanial** [comment] 2017-04-13 12:12
These lines of ``fth/file.fth`` confuse cloc:
<pre>
136 : (  ( "comment<rparen>"  -- )
137     source-id
138     CASE
139         -1 OF postpone ( ENDOF
140         0  OF postpone ( ENDOF
141         \ for input from files
142         multi-line-comment
143     ENDCASE
144 ; immediate
</pre>
The issue is the open paren's on lines 136, 139, and 140 without corresponding close paren's.  cloc expects an open paren to mark the beginning of a comment, then goes searching for the corresponding close paren--which are missing in this file.

``eval/eval1957.SACunidir.fr`` was interesting in that there were balanced parentheses but the code hung the same way as with ``fth/file.fth``.  It revealed a logic bug in cloc.

git commit ba37075 fixes both situations but it is possible the count of comment lines will be incorrect if parentheses are not balanced.

**Closed by AlDanial** 2017-04-13 12:12 UTC
