### ISSUE TITLE
Subexpression recursion limit exceeded

### ISSUE THREAD

**Issue by WladdGorshenin** [AlDanial/cloc#305] opened 2018-06-18 12:32 UTC
Hi,

Recently I got the following warning: 
Complex regular subexpression recursion limit (32766) exceeded at /home/jovyan/work/cloc-1.76.pl line 9998.

Could you please have a look at it.

**Comment by Montesdodgers13** [comment] 2018-06-18 16:05
Can you help me with this issue

**Comment by AlDanial** [comment] 2018-06-20 02:52
A few comments:  
* This is a duplicate of #245; please watch that for progress.
* The problem in question has no obvious solution so it may be a long time before I devise a work-around.
* If you submit new issues in the future, please include steps--including a path to input data I can use--to duplicate the exact problem you're facing.  Neither of the problem reports above give me anything I can work with.

**Closed by AlDanial** 2018-06-20 02:52 UTC
