### ISSUE TITLE
Hangs with high CPU on it's own source code

### ISSUE THREAD

**Issue by markasoftware** [AlDanial/cloc#192] opened 2017-05-08 03:02 UTC
Running the following hangs with perl at 100% CPU. I let it run for a couple hours before killing it on a pretty powerful machine.

`git clone --depth 1 https://github.com/AlDanial/cloc /tmp/cloc && cloc /tmp/cloc`

It counts the files, displays number of unique files, and that's it.

**Comment by AlDanial** [comment] 2017-05-08 04:10
I'm unable to reproduce this.  On my modest laptop running Ubuntu 16.04, the command
<pre>time ( git clone --depth 1 https://github.com/AlDanial/cloc /tmp/cloc && cloc /tmp/cloc )</pre>
finishes in less than three seconds after showing the complete set of results (98 lines of output):
<pre>
real    0m2.239s
user    0m0.508s
sys     0m0.204s
</pre>
Can you provide more details like OS, and also the last few lines of output of `cloc -v 3 /tmp/cloc` ?  I'm guessing somehow a non-cloc huge file got in there.

**Comment by markasoftware** [comment] 2017-05-08 04:38
Strange. I'm on Arch Linux. [Here's the output with `-v 3`](http://sprunge.us/KbCK). I'll look into it more tomorrow.

**Comment by AlDanial** [comment] 2017-05-08 04:49
Looks like it hangs in subroutine `Forth_paren_to_C()` -- entirely possible since that has a `while` loop with no max iteration check.  As to why the loop executes differently on Arch v. Ubuntu is a mystery.
Fortunately there are only two Forth files in the cloc distribution.  Try to count just them with
<pre>
cloc -v 3 --by-file /tmp/cloc/tests/inputs/issues/183
</pre>
If it hangs there we'll at a minimum be able to identify the offending file.

**Comment by markasoftware** [comment] 2017-05-08 14:50
Yep, it hangs doing that command as well, here's the output (seems the same as from other one):

```
-> make_file_list(/tmp/cloc/tests/inputs/issues/183)
Using temp file list [/tmp/zcC7Nlq5Xf]
-> find_preprocessor(/tmp/cloc/tests/inputs/issues/183)
<- find_preprocessor(file.fth eval1957.SACunidir.fr)
       2 text files.
classifying /tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr
-> classify_file(/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr)
/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr extension=[fr]
classifying /tmp/cloc/tests/inputs/issues/183/file.fth
-> classify_file(/tmp/cloc/tests/inputs/issues/183/file.fth)
/tmp/cloc/tests/inputs/issues/183/file.fth extension=[fth]
<- make_file_list()
-> remove_duplicate_files
<- remove_duplicate_files
       2 unique files.                              
-> call_counter(/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr, Forth)
-> read_file(/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr)
<- read_file
-> rm_blanks(language=Forth)
-> remove_matches(pattern=^\s*$)
<- remove_matches
<- rm_blanks(language=Forth)
-> rm_comments(file=/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr)
rm_comments file=/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr sub=remove_matches
-> remove_matches(pattern=^\s*\\.*$)
<- remove_matches
-> remove_matches(pattern=^\s*$)
<- remove_matches
rm_comments file=/tmp/cloc/tests/inputs/issues/183/eval1957.SACunidir.fr sub=Forth_paren_to_C
-> Forth_paren_to_C()
```

I can also confirm that this occurs on my other computer (which is running Arch as well). I also tried downloading from the releases page rather than the official Arch package, but the same issue occurs. It works fine on repos without forth in them.

**Comment by AlDanial** [comment] 2017-05-09 04:28
I was mistaken about the ``while`` loop in ``Forth_paren_to_C()`` not having a max iteration count--it does.  Issue #183 does in fact trigger this limit because it has unbalanced parentheses (which denote comments in Forth).  To help figure out why Arch behaves differently from Linux please replace ``Forth_paren_to_C()``, which begins at line 5203 in the latest commit, with this instrumented version:
<pre>
sub Forth_paren_to_C  {                      # {{{1
    my ($ra_lines, ) = @_; 
    # Converts Forth comment parentheses to C comments.

    print "-> Forth_paren_to_C()\n" if $opt_v > 2;

    my $in_comment = 0;
    my $max_paren_pair_per_line = 255;
    foreach (@{$ra_lines}) {
print "Forth_paren_to_C: [$_]\n";
        my $n_iter = 0;
        while (/\s\(\s/ or ($in_comment and /\)/)) {
print "TOP n_iter=$n_iter in_comment=$in_comment\n";
            if (/\s\(\s.*?\)/) {
                # in-line parenthesis comment; handle here
                s/\s+\(\s+.*?\)//g;
print "B\n";
            } elsif (!$in_comment and /\s\(\s/) {
                s{\s+\(\s+}{/*};
print "C\n";
                $in_comment = 1;
            } elsif ($in_comment and /\)/) {
                s{\)}{*/};
print "D\n";
                $in_comment = 0;
            } else {
                # gets here if it can't find a matching
                # close parenthesis; in this case the
                # results will likely be incorrect
                ++$n_iter;
print "E\n";
                last if $n_iter > $max_paren_pair_per_line;
            }
        }
    }

    print "<- Forth_paren_to_C\n" if $opt_v > 2;
    return @{$ra_lines};
} # 1}}}
</pre>
then post cloc's output with ``cloc/tests/inputs/issues/183/file.fth`` as the sole input.

**Comment by AlDanial** [comment] 2017-05-09 04:41
typo:  "...why Arch behaves differently from Linux..."  I know Arch is Linux, I meant "...why Arch behaves differently from Ubuntu..."

**Comment by AlDanial** [comment] 2017-06-02 16:54
I installed archlinux-2017.06.01-x86_64.iso into a VirtualBox VM on my Ubuntu 16.04 system, installed cloc by cloning the repo, then counted its own contents.  Worked without issue.  Closing since I can't duplicate the problem.

**Closed by AlDanial** 2017-06-02 16:54 UTC

**Comment by markasoftware** [comment] 2017-06-14 02:05
Sorry for super late response. I was able to resolve this by cloning the cloc repo and using the latest commit. The releases page and official arch package still hang. I guess they just need to be updated to the latest git version.
