### ISSUE TITLE
The subroutine "Raku_or_Prolog" is missing in cloc (1.86)

### ISSUE THREAD

**Issue by jschleus** [AlDanial/cloc#514] opened 2020-08-19 07:22 UTC
The subroutine `Raku_or_Prolog` (used for the extensions `.p6` and `.P6`) is missing in `cloc`.

**Comment by AlDanial** [comment] 2020-08-20 03:42
Duplicate of #510.  This is fixed in the development version in case you want to try that.

**Closed by AlDanial** 2020-08-20 03:42 UTC

**Comment by jschleus** [comment] 2020-08-20 07:16
Grrh, I have forgotten to check the closed issues. But I searched in the current `cloc` but probably insufficiently :-(
